image:
  name: hashicorp/terraform:0.14.3
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - Test and Lint
  - Build and Push
  - Buildx and Push
  - Stage Plan
  - Stage Apply
  - Production Plan
  - Production Apply
  - Destroy

Validate Terraform:
  stage: Test and Lint
  script:
    - cd terraform/
    - terraform init -backend=false
    - terraform init validate
    - terraform fmt -check
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^(master|stage)$/ || $CI_COMMIT_BRANCH =~ /^(master|stage)$/'

Build and Push:
  stage: Build and Push
  image: docker:20.10
  services:
    - docker:20.10-dind
  script:
    - apk add python3 py3-pip
    - pip3 install awscli
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/e7k4f6o3
    - docker build --compress -t $ECR_REPO:$CI_COMMIT_SHORT_SHA -t $ECR_REPO:latest .
    - docker push $ECR_REPO:$CI_COMMIT_SHORT_SHA && docker push $ECR_REPO:latest
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(master|stage)$/'

Buildx and Push:
  stage: Buildx and Push
  image: docker:20.10
  services:
    - name: docker:20.10-dind
      command: ["--experimental"]
  before_script:
    - export BUILDX_VERSION="v0.5.0"
    - curl -sSLo docker-buildx "https://github.com/docker/buildx/releases/download/$BUILDX_VERSION/buildx-$BUILDX_VERSION.linux-amd64"
    - chmod a+x docker-buildx
    - mkdir -p ~/.docker/cli-plugins
    - mv buildx ~/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use --name mybuilder
  script:
    - docker login -u $HUB_USER -p $HUB_PASSWORD
    - export DATE=$(date +%Y-%m-%d)
    - docker buildx build --platform linux/amd64,linux/arm64 -t $HUB_REPO:$DATE -t $HUB_REPO:latest . --push
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

Stage Plan:
  stage: Stage Plan
  script:
    - cd terraform/
    - export TF_VAR_ecr_image_resume=$ECR_REPO:$CI_COMMIT_SHORT_SHA
    - terraform init
    - terraform workspace select stage || terraform workspace new stage
    - terraform plan
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage"'

Stage Apply:
  stage: Stage Apply
  script:
    - cd terraform/
    - export TF_VAR_ecr_image_resume=$ECR_REPO:$CI_COMMIT_SHORT_SHA
    - terraform init
    - terraform workspace select stage
    - terraform apply -auto-approve
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage"'
      when: manual

Production Plan:
  stage: Production Plan
  script:
    - cd terraform/
    - export TF_VAR_ecr_image_resume=$ECR_REPO:$CI_COMMIT_SHORT_SHA
    - terraform init
    - terraform workspace select prod || terraform workspace new prod
    - terraform plan
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

Production Apply:
  stage: Production Apply
  script:
    - cd terraform/
    - export TF_VAR_ecr_image_resume=$ECR_REPO:$CI_COMMIT_SHORT_SHA
    - terraform init
    - terraform workspace select prod
    - terraform apply -auto-approve
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: manual

Stage Destroy:
  stage: Destroy
  script:
    - cd terraform/
    - terraform init
    - terraform workspace select stage
    - terraform destroy -auto-approve
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage"'
      when: manual

Production Destroy:
  stage: Destroy
  script:
    - cd terraform/
    - terraform init
    - terraform workspace select prod
    - terraform destroy -auto-approve
  only:
    variables:
      - $PRODUCTION_DESTROY == "True"
